/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFairsNewRouteImport } from './routes/_authenticated/fairs.new'
import { Route as AuthenticatedFairsFairIdRouteImport } from './routes/_authenticated/fairs.$fairId'
import { Route as AuthenticatedFairsFairIdScheduleRouteImport } from './routes/_authenticated/fairs.$fairId.schedule'
import { Route as AuthenticatedFairsFairIdMapRouteImport } from './routes/_authenticated/fairs.$fairId.map'
import { Route as AuthenticatedFairsFairIdExhibitorsNewRouteImport } from './routes/_authenticated/fairs.$fairId.exhibitors.new'
import { Route as AuthenticatedFairsFairIdExhibitorsExhibitorIdRouteImport } from './routes/_authenticated/fairs.$fairId.exhibitors.$exhibitorId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFairsNewRoute = AuthenticatedFairsNewRouteImport.update({
  id: '/fairs/new',
  path: '/fairs/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFairsFairIdRoute =
  AuthenticatedFairsFairIdRouteImport.update({
    id: '/fairs/$fairId',
    path: '/fairs/$fairId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFairsFairIdScheduleRoute =
  AuthenticatedFairsFairIdScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedFairsFairIdRoute,
  } as any)
const AuthenticatedFairsFairIdMapRoute =
  AuthenticatedFairsFairIdMapRouteImport.update({
    id: '/map',
    path: '/map',
    getParentRoute: () => AuthenticatedFairsFairIdRoute,
  } as any)
const AuthenticatedFairsFairIdExhibitorsNewRoute =
  AuthenticatedFairsFairIdExhibitorsNewRouteImport.update({
    id: '/exhibitors/new',
    path: '/exhibitors/new',
    getParentRoute: () => AuthenticatedFairsFairIdRoute,
  } as any)
const AuthenticatedFairsFairIdExhibitorsExhibitorIdRoute =
  AuthenticatedFairsFairIdExhibitorsExhibitorIdRouteImport.update({
    id: '/exhibitors/$exhibitorId',
    path: '/exhibitors/$exhibitorId',
    getParentRoute: () => AuthenticatedFairsFairIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fairs/$fairId': typeof AuthenticatedFairsFairIdRouteWithChildren
  '/fairs/new': typeof AuthenticatedFairsNewRoute
  '/fairs/$fairId/map': typeof AuthenticatedFairsFairIdMapRoute
  '/fairs/$fairId/schedule': typeof AuthenticatedFairsFairIdScheduleRoute
  '/fairs/$fairId/exhibitors/$exhibitorId': typeof AuthenticatedFairsFairIdExhibitorsExhibitorIdRoute
  '/fairs/$fairId/exhibitors/new': typeof AuthenticatedFairsFairIdExhibitorsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fairs/$fairId': typeof AuthenticatedFairsFairIdRouteWithChildren
  '/fairs/new': typeof AuthenticatedFairsNewRoute
  '/fairs/$fairId/map': typeof AuthenticatedFairsFairIdMapRoute
  '/fairs/$fairId/schedule': typeof AuthenticatedFairsFairIdScheduleRoute
  '/fairs/$fairId/exhibitors/$exhibitorId': typeof AuthenticatedFairsFairIdExhibitorsExhibitorIdRoute
  '/fairs/$fairId/exhibitors/new': typeof AuthenticatedFairsFairIdExhibitorsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fairs/$fairId': typeof AuthenticatedFairsFairIdRouteWithChildren
  '/_authenticated/fairs/new': typeof AuthenticatedFairsNewRoute
  '/_authenticated/fairs/$fairId/map': typeof AuthenticatedFairsFairIdMapRoute
  '/_authenticated/fairs/$fairId/schedule': typeof AuthenticatedFairsFairIdScheduleRoute
  '/_authenticated/fairs/$fairId/exhibitors/$exhibitorId': typeof AuthenticatedFairsFairIdExhibitorsExhibitorIdRoute
  '/_authenticated/fairs/$fairId/exhibitors/new': typeof AuthenticatedFairsFairIdExhibitorsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/fairs/$fairId'
    | '/fairs/new'
    | '/fairs/$fairId/map'
    | '/fairs/$fairId/schedule'
    | '/fairs/$fairId/exhibitors/$exhibitorId'
    | '/fairs/$fairId/exhibitors/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/fairs/$fairId'
    | '/fairs/new'
    | '/fairs/$fairId/map'
    | '/fairs/$fairId/schedule'
    | '/fairs/$fairId/exhibitors/$exhibitorId'
    | '/fairs/$fairId/exhibitors/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/fairs/$fairId'
    | '/_authenticated/fairs/new'
    | '/_authenticated/fairs/$fairId/map'
    | '/_authenticated/fairs/$fairId/schedule'
    | '/_authenticated/fairs/$fairId/exhibitors/$exhibitorId'
    | '/_authenticated/fairs/$fairId/exhibitors/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fairs/new': {
      id: '/_authenticated/fairs/new'
      path: '/fairs/new'
      fullPath: '/fairs/new'
      preLoaderRoute: typeof AuthenticatedFairsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fairs/$fairId': {
      id: '/_authenticated/fairs/$fairId'
      path: '/fairs/$fairId'
      fullPath: '/fairs/$fairId'
      preLoaderRoute: typeof AuthenticatedFairsFairIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fairs/$fairId/schedule': {
      id: '/_authenticated/fairs/$fairId/schedule'
      path: '/schedule'
      fullPath: '/fairs/$fairId/schedule'
      preLoaderRoute: typeof AuthenticatedFairsFairIdScheduleRouteImport
      parentRoute: typeof AuthenticatedFairsFairIdRoute
    }
    '/_authenticated/fairs/$fairId/map': {
      id: '/_authenticated/fairs/$fairId/map'
      path: '/map'
      fullPath: '/fairs/$fairId/map'
      preLoaderRoute: typeof AuthenticatedFairsFairIdMapRouteImport
      parentRoute: typeof AuthenticatedFairsFairIdRoute
    }
    '/_authenticated/fairs/$fairId/exhibitors/new': {
      id: '/_authenticated/fairs/$fairId/exhibitors/new'
      path: '/exhibitors/new'
      fullPath: '/fairs/$fairId/exhibitors/new'
      preLoaderRoute: typeof AuthenticatedFairsFairIdExhibitorsNewRouteImport
      parentRoute: typeof AuthenticatedFairsFairIdRoute
    }
    '/_authenticated/fairs/$fairId/exhibitors/$exhibitorId': {
      id: '/_authenticated/fairs/$fairId/exhibitors/$exhibitorId'
      path: '/exhibitors/$exhibitorId'
      fullPath: '/fairs/$fairId/exhibitors/$exhibitorId'
      preLoaderRoute: typeof AuthenticatedFairsFairIdExhibitorsExhibitorIdRouteImport
      parentRoute: typeof AuthenticatedFairsFairIdRoute
    }
  }
}

interface AuthenticatedFairsFairIdRouteChildren {
  AuthenticatedFairsFairIdMapRoute: typeof AuthenticatedFairsFairIdMapRoute
  AuthenticatedFairsFairIdScheduleRoute: typeof AuthenticatedFairsFairIdScheduleRoute
  AuthenticatedFairsFairIdExhibitorsExhibitorIdRoute: typeof AuthenticatedFairsFairIdExhibitorsExhibitorIdRoute
  AuthenticatedFairsFairIdExhibitorsNewRoute: typeof AuthenticatedFairsFairIdExhibitorsNewRoute
}

const AuthenticatedFairsFairIdRouteChildren: AuthenticatedFairsFairIdRouteChildren =
  {
    AuthenticatedFairsFairIdMapRoute: AuthenticatedFairsFairIdMapRoute,
    AuthenticatedFairsFairIdScheduleRoute:
      AuthenticatedFairsFairIdScheduleRoute,
    AuthenticatedFairsFairIdExhibitorsExhibitorIdRoute:
      AuthenticatedFairsFairIdExhibitorsExhibitorIdRoute,
    AuthenticatedFairsFairIdExhibitorsNewRoute:
      AuthenticatedFairsFairIdExhibitorsNewRoute,
  }

const AuthenticatedFairsFairIdRouteWithChildren =
  AuthenticatedFairsFairIdRoute._addFileChildren(
    AuthenticatedFairsFairIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFairsFairIdRoute: typeof AuthenticatedFairsFairIdRouteWithChildren
  AuthenticatedFairsNewRoute: typeof AuthenticatedFairsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFairsFairIdRoute: AuthenticatedFairsFairIdRouteWithChildren,
  AuthenticatedFairsNewRoute: AuthenticatedFairsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
